add trivy

diff --git a/deployment/snapshot/Jenkinsfile b/deployment/snapshot/Jenkinsfile
--- a/deployment/snapshot/Jenkinsfile
+++ b/deployment/snapshot/Jenkinsfile
@@ -52,26 +52,21 @@ pipeline {
         }
 
         stage('Trivy Scan') {
-            agent {
-                docker {
-                    image 'aquasec/trivy'
-                    reuseNode true
-                }
-            }
-
             steps {
-                sh '''
-                    trivy ${env.registry}/${env.imageName}:${env.buildVersion}
-                    my_exit_code=$?
-                    echo "RESULT 1:--- $my_exit_code"
+                script {
+                    sh '''
+                        trivy --cache-dir /root/.trivy/trivy ${env.registry}/${env.imageName}:${env.buildVersion}
+                        my_exit_code=$?
+                        echo "RESULT 1:--- $my_exit_code"
 
-                    if [ ${my_exit_code} == 1]; then
-                        echo "Image scanning failed. Some vulnerabilities found"
-                        exit 1;
-                    else
-                        echo "Image is scanned Successfully. No vulnerabilities found"
-                    fi;
-                 '''
+                        if [ ${my_exit_code} == 1]; then
+                            echo "Image scanning failed. Some vulnerabilities found"
+                            exit 1;
+                        else
+                            echo "Image is scanned Successfully. No vulnerabilities found"
+                        fi;
+                     '''
+                 }
             }
         }
 
